"""replace assigned specialist with assigned user

Revision ID: 0baa8412b185
Revises: a862e8608a45
Create Date: 2026-07-17 09:39:35.063098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0baa8412b185'
down_revision: Union[str, Sequence[str], None] = 'a862e8608a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema (идемпотентно)."""

    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = {
        column["name"]
        for column in inspector.get_columns('tickets')
    }

    if 'assigned_user_id' not in existing_columns:
        op.add_column(
            'tickets',
            sa.Column('assigned_user_id', sa.Integer(), nullable=True)
        )
        op.create_index(
            op.f('ix_tickets_assigned_user_id'),
            'tickets',
            ['assigned_user_id'],
            unique=False
        )
        op.create_foreign_key(
            None, 'tickets', 'users', ['assigned_user_id'], ['id'],
            ondelete='SET NULL'
        )

    # На новых базах такой колонки уже нет с самого начала (в
    # свежем "baseline" её больше не создают) — на старых базах она
    # ещё может быть, тогда удаляем.
    if 'assigned_specialist' in existing_columns:
        op.drop_column('tickets', 'assigned_specialist')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_specialist', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_assigned_user_id'), table_name='tickets')
    op.drop_column('tickets', 'assigned_user_id')
    # ### end Alembic commands ###
