"""add roles and users

Revision ID: a862e8608a45
Revises: b81aa21cb569
Create Date: 2026-07-16 14:37:57.600846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a862e8608a45'
down_revision: Union[str, Sequence[str], None] = 'b81aa21cb569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema (идемпотентно).

    Изначально эта миграция только добавляла колонку "description" в
    таблицу "roles", предполагая, что сами таблицы "roles" и "users"
    уже существуют — они действительно существовали на уже работавших
    базах (созданные раньше напрямую из моделей, в обход Alembic), но
    на полностью новой базе (например, при первом запуске в Docker)
    таблиц ещё нет вообще, и ALTER TABLE падал с "relation does not
    exist". Теперь миграция сама создаёт обе таблицы, если их ещё
    нет — и на старых, и на новых базах результат одинаковый.
    """

    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    if 'roles' not in existing_tables:
        op.create_table(
            'roles',
            sa.Column('id', sa.Integer(), primary_key=True, index=True),
            sa.Column(
                'name',
                sa.String(length=100),
                nullable=False,
                unique=True
            ),
            sa.Column(
                'description',
                sa.String(length=255),
                nullable=True
            ),
        )
    else:
        existing_columns = {
            column["name"]
            for column in inspector.get_columns('roles')
        }
        if 'description' not in existing_columns:
            op.add_column(
                'roles',
                sa.Column('description', sa.String(length=255), nullable=True)
            )

    if 'users' not in existing_tables:
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), primary_key=True, index=True),
            sa.Column('full_name', sa.String(length=255), nullable=False),
            sa.Column(
                'username',
                sa.String(length=100),
                nullable=False,
                unique=True
            ),
            sa.Column(
                'email',
                sa.String(length=255),
                nullable=False,
                unique=True
            ),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column(
                'role_id',
                sa.Integer(),
                sa.ForeignKey('roles.id'),
                nullable=False
            ),
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            ),
            sa.Column(
                'created_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now()
            ),
        )
        op.create_index(op.f('ix_users_username'), 'users', ['username'])
        op.create_index(op.f('ix_users_email'), 'users', ['email'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
