"""add ticket creator and citizen role

Revision ID: d2f6a1b9c3e7
Revises: c1a2b3d4e5f6
Create Date: 2026-07-27 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f6a1b9c3e7'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Роль "Наблюдатель" переквалифицируется в обычного пользователя
# (жителя), который может создавать обращения и видеть только свои.
OLD_ROLE_NAME = "Наблюдатель"
NEW_ROLE_NAME = "Пользователь"
NEW_ROLE_DESCRIPTION = "Создаёт обращения и видит только свои"


def upgrade() -> None:
    """Upgrade schema (идемпотентно)."""

    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = {
        column["name"]
        for column in inspector.get_columns('tickets')
    }

    if 'created_by_user_id' not in existing_columns:
        op.add_column(
            'tickets',
            sa.Column('created_by_user_id', sa.Integer(), nullable=True)
        )
        op.create_index(
            op.f('ix_tickets_created_by_user_id'),
            'tickets',
            ['created_by_user_id'],
            unique=False
        )
        op.create_foreign_key(
            'fk_tickets_created_by_user_id_users',
            'tickets',
            'users',
            ['created_by_user_id'],
            ['id'],
            ondelete='SET NULL'
        )

    # Переименовываем существующую роль "Наблюдатель" в "Пользователь".
    # Если роли "Наблюдатель" не было — создаём "Пользователь" с нуля,
    # чтобы регистрация новых жителей работала в любом случае.
    connection = op.get_bind()

    roles = sa.table(
        "roles",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
    )

    existing_old = connection.execute(
        sa.select(roles.c.id).where(roles.c.name == OLD_ROLE_NAME)
    ).first()

    existing_new = connection.execute(
        sa.select(roles.c.id).where(roles.c.name == NEW_ROLE_NAME)
    ).first()

    if existing_new is not None:
        pass
    elif existing_old is not None:
        connection.execute(
            roles.update()
            .where(roles.c.id == existing_old.id)
            .values(name=NEW_ROLE_NAME, description=NEW_ROLE_DESCRIPTION)
        )
    else:
        connection.execute(
            roles.insert().values(
                name=NEW_ROLE_NAME,
                description=NEW_ROLE_DESCRIPTION,
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    connection = op.get_bind()

    roles = sa.table(
        "roles",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
    )

    connection.execute(
        roles.update()
        .where(roles.c.name == NEW_ROLE_NAME)
        .values(name=OLD_ROLE_NAME)
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_tickets_created_by_user_id_users',
        'tickets',
        type_='foreignkey'
    )
    op.drop_index(
        op.f('ix_tickets_created_by_user_id'),
        table_name='tickets'
    )
    op.drop_column('tickets', 'created_by_user_id')
    # ### end Alembic commands ###
